### ISSUE TITLE
HA VM Restart Plugin Time incorrect

### ISSUE THREAD

**Issue by dirtridermtb** [alanrenouf/vCheck-vSphere#477]
Please look into HA VM restart plugin, the time in the report says 11/08/2016 12:32:22 AM for vSphere HA restarted virtual machine John10Test on host b1pdevesx02.bnemain.local in cluster b1-dev-cluster 

Upon investigation in vSphere Web Client, it actually occured at 

Description	Type	Date Time	Task	Target	User
vSphere HA restarted this virtual machine	Warning	11/08/2016 10:32:22 AM		John10Test

**Comment by vbakshi123** [comment]
I have seen the same issue. Its not only HA VM restart, but all the alarms and all entries from other plugins are around 2 hrs ahead. Need this fixed

**Comment by Sneddo** [comment]
Looks like the time is reported in UTC potentially...should be simple enough to convert to local time.

**Comment by dirtridermtb** [comment]
If you can please update us when it is fixed and how to apply the updates?
Is it just downloading the latest revision of the package vCheck?

**Comment by Sneddo** [comment]
I've just pushed a couple of updates which should fix this issue. Haven't had a chance to test, so let me know if anything breaks. Basically, anything that uses Get-VIEventPlus to retrieve events should now return them in local time rather than UTC, and the HA restart plugin now uses Get-VIEventPlus instead of duplicating the search code.

You will need to update two plugin files:
1. [Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1](https://raw.githubusercontent.com/alanrenouf/vCheck-vSphere/dev/Plugins/00%20Initialize/00%20Connection%20Plugin%20for%20vCenter.ps1)
2. [Plugins/20 Cluster/15 HA VMs restarted.ps1](https://raw.githubusercontent.com/alanrenouf/vCheck-vSphere/dev/Plugins/20%20Cluster/15%20HA%20VMs%20restarted.ps1)

Just replace your existing plugins with these.

**Comment by vbakshi123** [comment]
Will check it out today and see the results

**Comment by vbakshi123** [comment]
Hey Sneddo, I checked it out and the results are the same. The difference in time that I always is of 2 hrs or 5 hrs. Moreoever, the 00 Connection Plugin file that you attached to your last comment on this post, is the same that I had downloaded a week back. The Get-VIEventPlus is there as the last function. By reading your post, I had changed the other Get-VIEvent to Get-VIEventlus in function Get-VMLastPoweredOffDate and function Get-VMLastPoweredOnDate. But results are, the time is still way ahead by 2 hrs or 5 hrs.
The function Get-VIEventPlus  section at the end was always like this.

**Comment by Sneddo** [comment]
Are you running the VCSA or vCenter on Windows? Do you have time configured correctly? What timezone are you in? I've just tested and the events are returning the correct times for me in UTC+10. 

If the function is exactly the same, you did something wrong- there is around 10 lines different between the version from yesterday and last week. Maybe you downloaded the master branch not dev?

I've also committed the change to the Get-VMLastPoweredOffDate and Get-VMLastPoweredOnDate functions, good catch on that one.

**Comment by dirtridermtb** [comment]
FYI the time is fixed for me after the changes 
********************************************************************
You will need to update two plugin files:
1. Plugins/00 Initialize/00 Connection Plugin for vCenter.ps1
2. Plugins/20 Cluster/15 HA VMs restarted.ps1

Just replace your existing plugins with these.
********************************************************************

Thanks for fixing the others. Also might pay to check ESX/ESXi VMkernel Warnings plugin & Host Alarms, VMs created or cloned, VMs removed and any other plugin that uses time. Thanks heaps

**Comment by Sneddo** [comment]
Yeah, I suspect there will be a few other plugins that need to be updated. I'll try searching through the code base to pick them up

**Comment by vbakshi123** [comment]
Hey Sneddo, I downloaded the 00 connection plugin ps1 file from Dev and yes I do see the new entries of UTC in that code. However, even after I run it, the time still shows the time difference. I am running the script from a Windows vCenter which has the time zone, EMEA server (UTC+01:00 Brussels, Copenhagen, Madrid & Paris) and its connecting to a vCenter which has a time zone of US, ie. (GMT-5:00 Eastern Time US & Canada) Any thoughts ?? The time difference is 4 hrs in this case, for some other vcenter servers, the report it pulls has a time difference of 2 hrs or 5 hrs. Moreoever, I also checked the other plugins like "Host Alarms.ps1" and it doesn't have any code with Get-VIEvent

**Comment by Sneddo** [comment]
The time difference of 5 hours _may_ make sense then, if the time is returned in UTC. I wonder how the Windows vCenter records time, whether this is based on the system clock instead of UTC...? I don't have a Windows vCenter to test this out on, and seems like running the script in a different timezone to the vCenter further complicates things.

Out of interest, what happens if you run vCheck from a machine within the same timezone as your vCenters? Do you get the time differences on both vCenters?

**Comment by SkipHorn** [comment]
The vCHECK "Lost Access to Volume"  messages are also being displayed in  UTC time - since the ESXI hosts must use UTC.  Can you patch this plugin to also use local time? Is it possible to send me the new plugin to test for you?  SKIP.HORN@ROCHESTER.EDU
https://github.com/alanrenouf/vCheck-vSphere/blob/4cd0c5c7d5d918187e69befaa52a8afaa2be8b23/Plugins/30%20Host/77%20Lost%20Access%20to%20Volume.ps1

**Comment by lucdekens** [comment]
Add option to define Timezone for reporting
